### PR TITLE
add containKeys

### PR DESCRIPTION
**Pull request by coderhaoxin**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
different to 
```js
({ a: 1, b: 2 }).should.have.keys('a', 'b');
```
sometimes, I only care about whether it contains particular keys.
especially for api response.

```js
({ wanted: 1, others: 2 }).should.containKeys('wanted');
```

**Comment by btd** [comment]
Thanks for PR, but i will not merge it. There are already .any modifier and .keys. So need to apply .any to .keys instead of creating method with the same semantics.

**Comment by coderhaoxin** [comment]
just find `should.have.properties` works for this

**Comment by btd** [comment]
Yes, but it is not only enumerables). But anyway i will add .enumerables.

**Pull request closed without merging**
