### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by btd** [comment]
Thanks you, but can you rebase your PR, it is not ok to have each commit chaning 1 word.

**Comment by jsoref** [comment]
@btd: sure.

It's just much easier for me to drop things if I keep them in this form if you object to any of the individual corrections.

If you're comfortable with all of the changes, I'm happy to rebase + squash.

I'm going to take your comment as indicating you're ok w/ them (I'm currently splitting/resequencing for a different repo).

**Comment by jsoref** [comment]
@btd folded

**Comment by btd** [comment]
Thank you

**Pull request merged**
